/*
 * Generated by tools/hanzi_pipeline/build_hanzi_data.py -- do not edit.
 *
 * Stroke data derived from Make Me a Hanzi via hanzi-writer-data,
 * whose outlines come from the Arphic PL fonts under the Arphic
 * Public License. Character lists and pinyin from shukong-app.
 */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char hanzi_data_blob[];
extern const unsigned int hanzi_data_blob_size;

#ifdef __cplusplus
}
#endif
