#!/usr/bin/env python3
"""Generate the AppMath launcher icon.

Same house style as tools/hanzi_pipeline/make_icon.py -- black background, a
glowing rounded plate, a white symbol on top -- but in blue rather than
vermilion so a child can tell the two icons apart at a glance without reading
the labels. The symbol is a plus beside a minus, drawn as geometry rather than glyphs
so the two stroke weights match exactly.

Usage: python3 tools/math_pipeline/make_icon_math.py
"""

import os

from PIL import Image, ImageDraw, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT_C = os.path.join(REPO, "main", "assets", "images", "icon_math.c")
CACHE = os.path.join(REPO, "tools", "math_pipeline", ".cache")

SIZE = 200
SS = 4                     # supersampling
RADIUS_FRAC = 0.30         # corner radius as a fraction of the plate
PLATE_FRAC = 0.76          # plate size as a fraction of the icon
TOP = (86, 176, 255)       # sky blue, top of the gradient
BOTTOM = (40, 96, 214)     # deeper cobalt, bottom
GLOW = (58, 140, 255)

# Symbol geometry, as fractions of the symbol box. The two signs sit side by
# side rather than stacked -- stacked they read as a single ± sign, which is
# not what the app does.
STROKE_FRAC = 0.115        # bar thickness
ARM_FRAC = 0.19            # half-length of every bar
PLUS_CX_FRAC = 0.25
MINUS_CX_FRAC = 0.75


def rounded_plate(size, radius, top, bottom):
    """Vertical gradient clipped to a rounded square, as RGB + alpha mask."""
    grad = Image.new("RGB", (size, size))
    px = grad.load()
    for y in range(size):
        t = y / max(1, size - 1)
        row = tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(3))
        for x in range(size):
            px[x, y] = row
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, size - 1, size - 1], radius=radius,
                                           fill=255)
    return grad, mask


def symbol_mask(size):
    """White coverage mask: a plus beside a minus, both with rounded ends."""
    mask = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(mask)

    half = size * STROKE_FRAC / 2
    arm = size * ARM_FRAC
    cy = size / 2
    radius = half  # fully rounded bar ends

    def bar(cx, horizontal):
        if horizontal:
            box = [cx - arm, cy - half, cx + arm, cy + half]
        else:
            box = [cx - half, cy - arm, cx + half, cy + arm]
        draw.rounded_rectangle(box, radius=radius, fill=255)

    plus_cx = size * PLUS_CX_FRAC
    bar(plus_cx, horizontal=True)
    bar(plus_cx, horizontal=False)
    bar(size * MINUS_CX_FRAC, horizontal=True)

    return mask


def build():
    big = SIZE * SS
    canvas = Image.new("RGB", (big, big), (0, 0, 0))

    plate_size = int(big * PLATE_FRAC)
    radius = int(plate_size * RADIUS_FRAC)
    plate, plate_mask = rounded_plate(plate_size, radius, TOP, BOTTOM)
    offset = (big - plate_size) // 2

    # Outer bloom: the plate silhouette, blurred and added under the plate.
    glow = Image.new("RGB", (big, big), (0, 0, 0))
    glow.paste(Image.new("RGB", (plate_size, plate_size), GLOW), (offset, offset),
               plate_mask)
    glow = glow.filter(ImageFilter.GaussianBlur(radius=big * 0.055))
    canvas = Image.blend(canvas, glow, 0.85)

    canvas.paste(plate, (offset, offset), plate_mask)

    ssize = int(plate_size * 0.88)
    smask = symbol_mask(ssize)
    soff = (big - ssize) // 2
    white = Image.new("RGB", (ssize, ssize), (255, 255, 255))
    canvas.paste(white, (soff, soff), smask)

    return canvas.resize((SIZE, SIZE), Image.LANCZOS)


def emit_c(img, path):
    px = img.convert("RGB").load()
    data = bytearray()
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b = px[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            data += bytes((v & 0xFF, (v >> 8) & 0xFF))

    with open(path, "w", encoding="utf-8") as f:
        f.write("""#ifdef __has_include
#if __has_include("lvgl.h")
#ifndef LV_LVGL_H_INCLUDE_SIMPLE
#define LV_LVGL_H_INCLUDE_SIMPLE
#endif
#endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMAGE_ICON_MATH
#define LV_ATTRIBUTE_IMAGE_ICON_MATH
#endif

/* Generated by tools/math_pipeline/make_icon_math.py -- do not edit. */

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMAGE_ICON_MATH uint8_t icon_math_map[] = {
""")
        for i in range(0, len(data), 19):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 19]) + ",\n")
        f.write("""};

const lv_image_dsc_t icon_math = {
    .header.cf    = LV_COLOR_FORMAT_RGB565,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w     = %d,
    .header.h     = %d,
    .data_size    = %d * 2,
    .data         = icon_math_map,
};
""" % (SIZE, SIZE, SIZE * SIZE))
    return len(data)


def main():
    img = build()
    os.makedirs(CACHE, exist_ok=True)
    preview = os.path.join(CACHE, "icon_math.png")
    img.save(preview)
    size = emit_c(img, OUT_C)
    print(f"icon: {SIZE}x{SIZE} RGB565, {size} bytes -> {OUT_C}")
    print(f"preview: {preview}")


if __name__ == "__main__":
    main()
