#!/usr/bin/env python3
"""Generate the AppHanzi launcher icon.

Matches the house style of the other launcher icons: black background, a glowing
rounded shape, a white symbol on top. The symbol is 永 -- the character whose
eight strokes are the classical primer for Chinese calligraphy -- rendered from
the same stroke outlines the app itself uses.

Usage: python3 tools/hanzi_pipeline/make_icon.py
"""

import json
import os
import sys

from PIL import Image, ImageDraw, ImageFilter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_hanzi_data import (CACHE, COORD_SCALE, STROKE_CACHE, load_strokes,
                              normalise_char, outline_polygon)

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
OUT_C = os.path.join(REPO, "main", "assets", "images", "icon_hanzi.c")

SIZE = 200
SS = 4                     # supersampling
GLYPH = "永"
RADIUS_FRAC = 0.30         # corner radius as a fraction of the plate
PLATE_FRAC = 0.76          # plate size as a fraction of the icon
TOP = (255, 104, 72)       # vermilion, top of the gradient
BOTTOM = (206, 38, 46)     # deeper cinnabar, bottom
GLOW = (255, 70, 60)


def rounded_plate(size, radius, top, bottom):
    """Vertical gradient clipped to a rounded square, as RGB + alpha mask."""
    grad = Image.new("RGB", (size, size))
    px = grad.load()
    for y in range(size):
        t = y / max(1, size - 1)
        row = tuple(int(top[i] + (bottom[i] - top[i]) * t) for i in range(3))
        for x in range(size):
            px[x, y] = row
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, size - 1, size - 1], radius=radius,
                                           fill=255)
    return grad, mask


def glyph_mask(size):
    """White coverage mask of the glyph at the given size."""
    raw = load_strokes(GLYPH)
    if raw is None:
        raise SystemExit(f"no stroke data cached for {GLYPH}; run the pipeline first")
    strokes = normalise_char(raw)
    mask = Image.new("L", (size, size), 0)
    draw = ImageDraw.Draw(mask)
    k = size / COORD_SCALE
    for s in strokes:
        poly = outline_polygon(s["ops"], s["outline"], steps=16)
        draw.polygon([(x * k, y * k) for x, y in poly], fill=255)
    return mask


def build():
    big = SIZE * SS
    canvas = Image.new("RGB", (big, big), (0, 0, 0))

    plate_size = int(big * PLATE_FRAC)
    radius = int(plate_size * RADIUS_FRAC)
    plate, plate_mask = rounded_plate(plate_size, radius, TOP, BOTTOM)
    offset = (big - plate_size) // 2

    # Outer bloom: the plate silhouette, blurred and added under the plate.
    glow = Image.new("RGB", (big, big), (0, 0, 0))
    glow.paste(Image.new("RGB", (plate_size, plate_size), GLOW), (offset, offset),
               plate_mask)
    glow = glow.filter(ImageFilter.GaussianBlur(radius=big * 0.055))
    canvas = Image.blend(canvas, glow, 0.85)

    canvas.paste(plate, (offset, offset), plate_mask)

    # The glyph sits slightly smaller than the plate so the strokes breathe.
    gsize = int(plate_size * 0.74)
    gmask = glyph_mask(gsize)
    goff = (big - gsize) // 2
    white = Image.new("RGB", (gsize, gsize), (255, 255, 255))
    canvas.paste(white, (goff, goff), gmask)

    return canvas.resize((SIZE, SIZE), Image.LANCZOS)


def emit_c(img, path):
    px = img.convert("RGB").load()
    data = bytearray()
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b = px[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            data += bytes((v & 0xFF, (v >> 8) & 0xFF))

    with open(path, "w", encoding="utf-8") as f:
        f.write("""#ifdef __has_include
#if __has_include("lvgl.h")
#ifndef LV_LVGL_H_INCLUDE_SIMPLE
#define LV_LVGL_H_INCLUDE_SIMPLE
#endif
#endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMAGE_ICON_HANZI
#define LV_ATTRIBUTE_IMAGE_ICON_HANZI
#endif

/* Generated by tools/hanzi_pipeline/make_icon.py -- do not edit. */

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMAGE_ICON_HANZI uint8_t icon_hanzi_map[] = {
""")
        for i in range(0, len(data), 19):
            f.write("    " + ", ".join(f"0x{b:02X}" for b in data[i:i + 19]) + ",\n")
        f.write("""};

const lv_image_dsc_t icon_hanzi = {
    .header.cf    = LV_COLOR_FORMAT_RGB565,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.w     = %d,
    .header.h     = %d,
    .data_size    = %d * 2,
    .data         = icon_hanzi_map,
};
""" % (SIZE, SIZE, SIZE * SIZE))
    return len(data)


def main():
    img = build()
    preview = os.path.join(CACHE, "icon_hanzi.png")
    os.makedirs(CACHE, exist_ok=True)
    img.save(preview)
    size = emit_c(img, OUT_C)
    print(f"icon: {SIZE}x{SIZE} RGB565, {size} bytes -> {OUT_C}")
    print(f"preview: {preview}")


if __name__ == "__main__":
    main()
