#!/usr/bin/env python3
"""Regenerate charlist.py, the tracked character table.

This is a one-shot generator, not part of the normal build: running
build_hanzi_data.py never needs it (or its dependencies). Re-run it only to
refresh charlist.py from new inputs, then review the diff before committing.

The table covers every character the stroke-data set can draw (about 9.5 k),
so the pinyin search reaches the whole of it. Characters that yield no usable
reading are left out -- with neither a lesson nor a syllable they would be
unreachable dead weight in the blob.

Inputs:
  --source        characters.csv from jaywcjlove/table-of-general-standard-
                  chinese-characters (MIT): the full 8105-character
                  《通用规范汉字表》(2013) in official order with curated
                  per-character readings ("hàn" or "cháng|zhǎng"). Grab it
                  from https://raw.githubusercontent.com/jaywcjlove/
                  table-of-general-standard-chinese-characters/HEAD/data/
                  characters.csv
  --strokes-list  one character per line: everything the stroke data source
                  provides. Enumerate hanzi-writer-data with
                  https://data.jsdelivr.com/v1/package/npm/
                  hanzi-writer-data@2.0.1/flat (single-char *.json entries).
                  Radical-block codepoints (U+2E80..U+2FDF) are dropped here:
                  they are building blocks, not characters anyone looks up.

Dependencies (generation-time only): pypinyin, wordfreq[cjk]  (both MIT).

What each dependency contributes:
  * readings come from the CSV where it covers a character (curated,
    complete); pypinyin fills in everything outside the 8105. The CSV's '|'
    lists are in alphabetical order, not usage order ("看 kān|kàn"), so
    pypinyin's non-heteronym reading is moved to the front when present:
    first reading == everyday reading.
  * wordfreq's zipf_frequency(char, 'zh') orders the table by modern-usage
    frequency (rank 1 = most frequent; ties, including the long zero-
    frequency tail, break by codepoint). Only the rank is stored.
    One important tier on top of raw frequency: characters inside the
    规范表 (the CSV) rank before everything outside it. wordfreq folds
    traditional forms onto their simplified twins, so without the tier 謹
    would sit right next to 谨 in every candidate list; tiered, the
    traditional/variant/rare tail stays reachable but never crowds the
    characters a child is actually looking for.

Readings containing combining diacritics or characters outside the pinyin
alphabet are dropped (rare interjection readings, or pypinyin echoing the
character back when it knows no reading).
"""

import argparse
import csv
import os
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
GSC_COUNT = 8105  # the full 通用规范汉字表

# Mirrors PINYIN_EXTRA in build_hanzi_data.py plus the ê family; a reading
# using anything else cannot be rendered or normalised downstream.
PINYIN_ALPHABET = set("abcdefghijklmnopqrstuvwxyz") | \
    set("āáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜüńňǹḿêếề")

TEMPLATE = '''\
"""笔画数据全集的字表 + 读音 + 频序（教材字之外的部分按此追加）。

Generated by make_char_table.py -- do not edit by hand; regenerate and
review the diff instead. See that script's docstring for sources
(readings: the 通用规范汉字表 CSV, pypinyin outside it; frequency rank:
wordfreq). Each line is "char<TAB>reading[ reading...]<TAB>rank" with
rank 1 = most frequent in modern usage and the first reading the most
common one.
"""

TABLE = """\\
{table}"""


def entries():
    """-> [(char, [reading, ...], rank)], sorted by rank ascending."""
    out = []
    for line in TABLE.splitlines():
        char, readings, rank = line.split("\\t")
        out.append((char, readings.split(" "), int(rank)))
    out.sort(key=lambda e: e[2])
    return out


def readings_of():
    """-> {char: [reading, ...]}"""
    return {char: readings for char, readings, _rank in entries()}
'''


def clean_reading(raw):
    """-> normalised reading, or None if unusable."""
    r = unicodedata.normalize("NFC", raw.strip())
    if not r or len(r) > 8:
        return None
    if any(unicodedata.combining(ch) for ch in r):
        return None
    if any(ch not in PINYIN_ALPHABET for ch in r):
        return None
    return r


def load_readings_csv(path):
    with open(path, encoding="utf-8") as f:
        rows = list(csv.reader(f))[1:]
    if len(rows) < GSC_COUNT:
        raise SystemExit(f"{path}: expected the full {GSC_COUNT}-row table, "
                         f"got {len(rows)} rows")
    table = {}
    for char, raw in rows[:GSC_COUNT]:
        readings = []
        for part in raw.split("|"):
            r = clean_reading(part)
            if r is not None and r not in readings:
                readings.append(r)
        if readings:
            table[char] = readings
    return table


def load_strokes_list(path):
    chars = []
    seen = set()
    for line in open(path, encoding="utf-8"):
        c = line.strip()
        if len(c) != 1 or c in seen:
            continue
        seen.add(c)
        if 0x2E80 <= ord(c) <= 0x2FDF:  # radical blocks: not characters
            continue
        if ord(c) > 0xFFFF:  # the blob stores u16 codepoints
            raise SystemExit(f"{c!r} is beyond the BMP")
        chars.append(c)
    return chars


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", required=True,
                    help="characters.csv of the 8105-character table")
    ap.add_argument("--strokes-list", required=True,
                    help="file listing every stroke-data character")
    ap.add_argument("--out", default=os.path.join(HERE, "charlist.py"))
    args = ap.parse_args()

    from pypinyin import Style, pinyin

    csv_readings = load_readings_csv(args.source)
    chars = load_strokes_list(args.strokes_list)
    print(f"stroke set: {len(chars)} chars, "
          f"{sum(1 for c in chars if c in csv_readings)} covered by the CSV")

    entries = []
    skipped = []
    promoted_misses = 0
    for char in chars:
        readings = list(csv_readings.get(char, []))
        if not readings:
            for cand in pinyin(char, style=Style.TONE, heteronym=True)[0][:3]:
                r = clean_reading(cand)
                if r is not None and r not in readings:
                    readings.append(r)
        if not readings:
            skipped.append(char)
            continue
        if len(readings) > 1:
            primary = clean_reading(pinyin(char, style=Style.TONE)[0][0])
            if primary in readings:
                readings.remove(primary)
                readings.insert(0, primary)
            else:
                promoted_misses += 1
        entries.append((char, readings))
    print(f"readings: pypinyin primary missing from the curated list for "
          f"{promoted_misses} chars (their order kept); "
          f"{len(skipped)} chars have no usable reading and are left out: "
          f"{''.join(skipped[:80])}{'...' if len(skipped) > 80 else ''}")

    from wordfreq import zipf_frequency
    ranked = sorted(entries,
                    key=lambda e: (e[0] not in csv_readings,
                                   -zipf_frequency(e[0], "zh"), ord(e[0])))

    lines = [f"{char}\t{' '.join(readings)}\t{rank + 1}"
             for rank, (char, readings) in enumerate(ranked)]
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(TEMPLATE.replace("{table}", "\n".join(lines) + "\n"))
    multi = sum(1 for _c, r in ranked if len(r) > 1)
    print(f"wrote {args.out}: {len(ranked)} characters, "
          f"{multi} with multiple readings")


if __name__ == "__main__":
    sys.exit(main())
