/*
 * Generated by tools/english_pipeline/build_english_data.py -- do not edit.
 *
 * Pictograms from ARASAAC (https://arasaac.org). Word audio is
 * re-encoded from a local dictionary bundle -- see the pipeline.
 */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/* Provided by the linker: main/CMakeLists.txt embeds
 * assets/english/english_data.bin via EMBED_FILES. */
extern const unsigned char english_data_blob[] asm("_binary_english_data_bin_start");
extern const unsigned char english_data_blob_tail[] asm("_binary_english_data_bin_end");

#define english_data_blob_size ((unsigned int)(english_data_blob_tail - english_data_blob))

#ifdef __cplusplus
}
#endif
